from .analysis import TOOL_DEFINITIONS as ANALYSIS_TOOLS
from .cache import TOOL_DEFINITIONS as CACHE_TOOLS
from .diagnostics import TOOL_DEFINITIONS as DIAGNOSTIC_TOOLS
from .management import TOOL_DEFINITIONS as MANAGEMENT_TOOLS
from .read import TOOL_DEFINITIONS as READ_TOOLS
from .write import TOOL_DEFINITIONS as WRITE_TOOLS

ALL_TOOL_DEFINITIONS = (
    *DIAGNOSTIC_TOOLS,
    *READ_TOOLS,
    *ANALYSIS_TOOLS,
    *CACHE_TOOLS,
    *WRITE_TOOLS,
    *MANAGEMENT_TOOLS,
)

